version: "3"
services:
  node:
    image: "node:lts-alpine"
    user: "node"
    working_dir: /home/node/app
    restart: unless-stopped
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
  nginx:
    image: "nginx:alpine"
    restart: unless-stopped
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file: ./docker/fqdn.env
    command: ["nginx", "-g", "daemon off;"]